stages:
 - build
 - test
 - upload

# multiarch images for jessie are no longer updated and were left in a bad state
.fix_jessie_multiarch_apt_sources: &fix_jessie_multiarch_apt
  /bin/sed -i 's/^\(.*jessie-updates main\)$/# \1/' /etc/apt/sources.list

# multiarch images only include the main component, and equivs is in universe
.fix_ubuntu_multiarch_apt_template: &fix_ubuntu_multiarch_apt
  /bin/sed -i 's/main$/main restricted universe/' /etc/apt/sources.list

.generic_apt_setup_template: &generic_apt_setup
  export DEBIAN_FRONTEND=noninteractive &&
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10no-recommends &&
  echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/10no-suggests &&
  apt-get update && apt-get -y upgrade &&
  apt-get install -y ca-certificates devscripts dpkg-dev equivs lsb-release wget gnupg apt-transport-https &&
  echo "deb https://dl.bintray.com/wand/amp `lsb_release -c -s` main" > /etc/apt/sources.list.d/amplet2.list &&
  wget -O- https://bintray.com/user/downloadSubjectPublicKey?username=wand | apt-key add - &&
  export DEBEMAIL='brendonj@waikato.ac.nz' &&
  export DEBFULLNAME='Brendon Jones' &&
  export CODENAME=`lsb_release -c -s` &&
  export ARCH=`dpkg-architecture -qDEB_HOST_ARCH` &&
  { wget -nv https://wand.net.nz/~brendonj/amp/youtube/chromium-libs_$CODENAME-$ARCH.tar.gz && tar xzvf chromium-libs_$CODENAME-$ARCH.tar.gz && echo "deb http://apt.llvm.org/${CODENAME}/ llvm-toolchain-${CODENAME} main" > /etc/apt/sources.list.d/llvm-toolchain.list && wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && export YOUTUBE="pkg.amplet2.build-youtube" || true; } &&
  { apt-get update || true; } &&
  { apt-cache show libpjproject-dev > /dev/null 2>&1 && export SIP="pkg.amplet2.build-sip" || true; } &&
  export DEB_BUILD_PROFILES="$YOUTUBE $SIP" &&
  mk-build-deps -i -r -t 'apt-get -f -y --force-yes'

.generic_apt_build_template: &generic_apt_build
  dpkg-buildpackage -b -us -uc -rfakeroot &&
  mkdir -p built-packages/$CODENAME/ || true &&
  mv ../*.deb built-packages/$CODENAME/

.build_template: &build_template
  stage: build
  script:
    - *generic_apt_setup
    - *generic_apt_build
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags
    - web

build-focal-amd64:
  <<: *build_template
  image: ubuntu:focal

build-focal-armhf:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:armhf-focal
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-focal-arm64:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:arm64-focal
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-bionic-amd64:
  <<: *build_template
  image: ubuntu:bionic

build-bionic-i386:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:i386-bionic
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-bionic-armhf:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:armhf-bionic
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-bionic-arm64:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:arm64-bionic
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-xenial-amd64:
  <<: *build_template
  image: ubuntu:xenial

build-xenial-i386:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:i386-xenial
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-xenial-armhf:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:armhf-xenial
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-xenial-arm64:
  <<: *build_template
  image: multiarch/ubuntu-debootstrap:arm64-xenial
  script:
    - *fix_ubuntu_multiarch_apt
    - *generic_apt_setup
    - *generic_apt_build

build-buster-amd64:
  <<: *build_template
  image: debian:buster

build-buster-i386:
  <<: *build_template
  image: multiarch/debian-debootstrap:i386-buster

build-buster-armhf:
  <<: *build_template
  image: multiarch/debian-debootstrap:armhf-buster

build-buster-arm64:
  <<: *build_template
  image: multiarch/debian-debootstrap:arm64-buster

build-stretch-amd64:
  <<: *build_template
  image: debian:stretch

build-stretch-i386:
  <<: *build_template
  image: multiarch/debian-debootstrap:i386-stretch

build-stretch-armhf:
  <<: *build_template
  image: multiarch/debian-debootstrap:armhf-stretch

build-stretch-arm64:
  <<: *build_template
  image: multiarch/debian-debootstrap:arm64-stretch

build-jessie-amd64:
  <<: *build_template
  image: debian:jessie

build-jessie-i386:
  <<: *build_template
  image: multiarch/debian-debootstrap:i386-jessie
  before_script:
    - *fix_jessie_multiarch_apt

build-jessie-armhf:
  <<: *build_template
  image: multiarch/debian-debootstrap:armhf-jessie
  before_script:
    - *fix_jessie_multiarch_apt

#build-jessie-arm64:
#  <<: *build_template
#  image: multiarch/debian-debootstrap:arm64-jessie

build-centos7-amd64:
  <<: *build_template
  image: centos:7
  script:
    - ./gitlab-build-rpm.sh

build-w32-amd64:
  <<: *build_template
  image: debian:buster
  script:
    - *generic_apt_setup
    - ./gitlab-build-w32.sh
  allow_failure: true


test-xenial-packages:
  stage: test
  image: ubuntu:xenial
  script:
    - *generic_apt_setup
    - ./gitlab-test-deb.sh
  only:
    - web
    - tags

test-bionic-packages:
  stage: test
  image: ubuntu:bionic
  script:
    - *generic_apt_setup
    - ./gitlab-test-deb.sh
  only:
    - web
    - tags

test-focal-packages:
  stage: test
  image: ubuntu:focal
  script:
    - *generic_apt_setup
    - ./gitlab-test-deb.sh
  only:
    - web
    - tags

test-jessie-packages:
  stage: test
  image: debian:jessie
  script:
    - *generic_apt_setup
    - ./gitlab-test-deb.sh
  only:
    - web
    - tags

test-stretch-packages:
  stage: test
  image: debian:stretch
  script:
    - *generic_apt_setup
    - ./gitlab-test-deb.sh
  only:
    - web
    - tags

test-buster-packages:
  stage: test
  image: debian:buster
  script:
    - *generic_apt_setup
    - ./gitlab-test-deb.sh
  only:
    - web
    - tags

test-centos7-packages:
  stage: test
  image: centos:7
  script:
    - ./gitlab-test-rpm.sh
  only:
    - web
    - tags

upload-packages:
  stage: upload
  image: ubuntu:bionic
  script:
    - ./bintray-upload.sh
  only:
    - tags
